CREATE DATABASE IF NOT EXISTS FOODMARKET;
USE FOODMARKET;

CREATE TABLE IF NOT EXISTS `ACCOUNTS` (
  `ACCOUNT_ID` varchar(64) NOT NULL DEFAULT 0,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(25) NOT NULL,
  `CREATED_AT` date NOT NULL,
  `EMAIL` varchar(35) NOT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
) ;

CREATE TABLE IF NOT EXISTS `SESSIONS` (
  `SESSION_ID` varchar(64) NOT NULL DEFAULT 0,
  `ACCOUNT_ID` varchar(64) NOT NULL DEFAULT 0,
  `STARTED_AT` DATETIME NOT NULL,
  `CLOSED_AT` DATETIME,
  PRIMARY KEY (`SESSION_ID`)
);

CREATE TABLE IF NOT EXISTS `LOCATIONS` (
  `LOCATION_ID` varchar(64) NOT NULL DEFAULT '0',
  `SESSION_ID` varchar(64) NOT NULL DEFAULT 0,
  `STREET_NAME` varchar(80) DEFAULT NULL,
  `STREET_NUMBER` varchar(4) DEFAULT NULL,
  `COMPLEMENT` varchar(20) DEFAULT NULL,
  `POSTAL_CODE` varchar(8) DEFAULT NULL,
  `CITY` varchar(30) NOT NULL,
  `STATE` varchar(25) DEFAULT NULL,
  `COUNTRY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`LOCATION_ID`)
) ;

CREATE TABLE IF NOT EXISTS `CARTS` (
  `CART_ID` varchar(64) NOT NULL DEFAULT 0,
  `SESSION_ID` varchar(64) NOT NULL DEFAULT 0,
  `TOTAL_AMOUNT_SPEND` FLOAT(6,2) NOT NULL,
  `CLOSED_CART` BOOLEAN NOT NULL DEFAULT FALSE,
  `HAS_ORDER` BOOLEAN NOT NULL DEFAULT FALSE, #TRIGGER INSERT NA ORDER_ID (ORDERS)
  PRIMARY KEY (`CART_ID`)
);

CREATE TABLE IF NOT EXISTS `PAYMENTS` (
  `PAYMENT_ID` varchar(64) NOT NULL DEFAULT 0,
  `CART_ID` varchar(64) NOT NULL DEFAULT 0,
  `PAYMENT_TYPE` varchar(15) DEFAULT NULL,
  `CARD_NUMBER` INT(16) DEFAULT NULL,
  `EXPIRATION_DATE` DATE NOT NULL,
  `CVC` INT(3) DEFAULT NULL,
  `APPROVED_PAYMENT` BOOLEAN NOT NULL DEFAULT FALSE, #TRIGGER UPDATE NA HAS_ORDERS (CARTS)
  PRIMARY KEY (`PAYMENT_ID`)
);

CREATE TABLE IF NOT EXISTS `ORDERS` (
  `ORDER_ID` varchar(64) NOT NULL DEFAULT 0,
  `PAYMENT_ID` varchar(64) NOT NULL DEFAULT 0,
  `CART_ID` varchar(64) NOT NULL DEFAULT 0,
  `DATE_ORDER` DATE NOT NULL,
  PRIMARY KEY (`ORDER_ID`)
);

CREATE TABLE IF NOT EXISTS `RATINGS` (
  `RATING_ID` varchar(64) NOT NULL DEFAULT 0,
  `ORDER_ID` varchar(64) NOT NULL DEFAULT 0,
  `RATING` INT NOT NULL DEFAULT 0, #COLOCAR VALORES ENTRE O E 5
  `DATE_RATING` DATE NOT NULL,
  PRIMARY KEY (`RATING_ID`)
);

CREATE TABLE IF NOT EXISTS `CART_ITEMS` (
  `CART_ID` varchar(64) NOT NULL DEFAULT 0,
  `ITEM_ID` varchar(64) NOT NULL DEFAULT 0,
  `QUANTITY` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`CART_ID`, `ITEM_ID`)
);

CREATE TABLE IF NOT EXISTS `CATALOG_ITEMS` (
  `ITEM_ID` varchar(64) NOT NULL DEFAULT 0,
  `MERCHANT_ID` varchar(64) NOT NULL DEFAULT 0,
  `ITEM_NAME` varchar(40) DEFAULT NULL,
  `ITEM_PRICE` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`)
);

CREATE TABLE IF NOT EXISTS `MERCHANTS` (
  `MERCHANT_ID` varchar(64) NOT NULL DEFAULT 0,
  `MERCHANT_NAME` varchar(40) DEFAULT NULL,
  `CUISINE_TYPE` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`MERCHANT_ID`)
);



